application: myresume-deliri
version: 1
runtime: go
api_version: go1
threadsafe: true
# default_expiration: "360d"
# instance_class: B1
# automatic_scaling:
#   min_idle_instances: 1
#   max_idle_instances: automatic  # default value
#   min_pending_latency: 30ms  # default value
#   max_pending_latency: automatic
#   max_concurrent_requests: 50
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /css
  static_dir: css
  expiration: "365d"

# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/\1
#   upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: _go_app
